/* No API keys, paid endpoints, or generated personal claims.
   A local profile retriever with curated answers and source links. */
(function(){
'use strict';
const facts=[
{id:'intro',keys:'who about introduction yourself background profile summary sai keerthana tell',title:'About Sai',text:'Sai Keerthana is a Senior AI Engineer with 10+ years across software, data engineering, machine learning, and enterprise AI. Her recent focus is agentic AI, RAG, secure integrations, evaluation, and production delivery across healthcare and financial services.',url:'/experience/'},
{id:'vatica',keys:'vatica health healthcare clinical hcc coding fhir hl7 current latest recent project',title:'Vatica Health',text:'At Vatica Health, Sai works as a GenAI Engineer (April 2024–present), developing RAG and LangGraph agent workflows for clinical coding support. Her résumé reports 24% improvement in HCC capture and 21% improvement in clinical coding support. The work includes HL7/FHIR integrations, evaluation, and AWS production deployment.',url:'/work/clinical-intelligence/'},
{id:'jpmc',keys:'jpmorgan jpmc chase finance financial azure banking bank',title:'JPMorgan Chase',text:'At JPMorgan Chase (April 2023–March 2024), Sai worked on financial knowledge systems with Azure OpenAI, LangChain, Weaviate, FastAPI, and AKS. Her résumé reports 29% improvement in throughput and 27% improvement in production runtime reliability.',url:'/work/financial-knowledge/'},
{id:'amazon',keys:'amazon search ranking relevance bm25 spark airflow',title:'Amazon',text:'At Amazon (January 2019–June 2020), Sai developed search retrieval and ranking workflows using Python, BM25, embeddings, behavioral signals, Spark, and Airflow. Her résumé reports a 25% improvement in query resolution and an 18% reduction in support escalations.',url:'/work/search-relevance/'},
{id:'costco',keys:'costco retail wholesale snowflake',title:'Costco Wholesale',text:'At Costco Wholesale (July 2020–December 2021), Sai worked as an ML Engineer on enterprise knowledge retrieval, search ranking, and retail analytics using NLP, Snowflake, PySpark, XGBoost, and Azure.',url:'/experience/'},
{id:'wisconsin',keys:'wisconsin state government public forecasting prediction',title:'State of Wisconsin',text:'As an AI/ML Engineer for the State of Wisconsin (January 2022–March 2023), Sai worked on demand forecasting, resource planning, and data pipelines using Python, Scikit-learn, TensorFlow, PySpark, and Azure.',url:'/experience/'},
{id:'goldman',keys:'goldman sachs legal compliance early first data engineer',title:'Goldman Sachs',text:'At Goldman Sachs (June 2016–December 2018), Sai worked as a Data Engineer on document intelligence and data pipelines supporting legal and compliance workflows with Python, NLP, Spark, PostgreSQL, and APIs.',url:'/experience/'},
{id:'agents',keys:'agent agents agentic langgraph langchain mcp tools tool orchestration state multiagent',title:'Agentic AI',text:'Sai’s experience includes LangGraph stateful workflows, routing, tool/function calling, MCP-compatible integrations, and multi-agent orchestration. She combines workflow constraints and tool-access controls with evaluation and observability.',url:'/systems/'},
{id:'rag',keys:'rag retrieval pinecone weaviate vector embeddings reranking knowledge grounded llamaindex',title:'Retrieval and RAG',text:'Sai develops grounded retrieval pipelines using chunking, embeddings, metadata filtering, semantic and hybrid retrieval, and reranking. Her toolkit includes Pinecone, Weaviate, FAISS, LangChain, and LlamaIndex. Try the working retrieval lab to inspect actual ranking and evaluation.',url:'/systems/#workflow'},
{id:'cloud',keys:'cloud aws gcp google azure kubernetes eks aks terraform docker deployment infrastructure',title:'Cloud delivery',text:'Her current Vatica work uses AWS as the primary cloud, with GCP as secondary experience. Her JPMorgan Chase work is Azure-based. Deployment experience includes Docker, Kubernetes, EKS/AKS, Terraform, CI/CD, and observability.',url:'/experience/#skills'},
{id:'evaluation',keys:'evaluation eval testing ragas langsmith langfuse llmops mlops quality monitoring drift hallucination',title:'Evaluation and operations',text:'Sai’s work includes golden datasets, offline and human-in-the-loop evaluations, groundedness, faithfulness, retrieval relevance, task completion, and regression quality gates. She uses Ragas, LangSmith, LangFuse, MLflow, Datadog, and cloud monitoring.',url:'/systems/'},
{id:'security',keys:'security secure guardrails governance hipaa injection risk controls permissions',title:'AI security and governance',text:'Her experience includes input/output validation, grounded retrieval, guardrails, controlled tool access, audit logging, and monitoring for regulated AI workflows. Her résumé describes familiarity with NIST AI RMF, OWASP LLM risks, and MITRE ATLAS principles.',url:'/experience/'},
{id:'skills',keys:'skills technologies stack python programming languages fastapi typescript react frameworks',title:'Technical skills',text:'Core areas include Python, SQL, FastAPI, LLM applications, LangGraph, LangChain, RAG, vector search, ML frameworks, data pipelines, cloud deployment, and MLOps/LLMOps. The experience page has a searchable inventory of her technologies.',url:'/experience/#skills'},
{id:'education',keys:'education degree college university bachelor study graduated qualification vnr',title:'Education',text:'Sai holds a bachelor’s degree in Computer Science from VNR Vignana Jyothi Institute of Engineering and Technology, India.',url:'/experience/'},
{id:'contact',keys:'contact email phone number reach connect hire hiring availability available contract opportunity resume cv linkedin github',title:'Contact and opportunities',text:'Sai is interested in contract opportunities in senior AI engineering, GenAI, agentic systems, RAG, and production ML. Email saikeerthanat.2614@gmail.com or call +1 (703) 420-7978. Specific availability, rate, and project commitments should be confirmed directly.',url:'/contact/'},
{id:'voice',keys:'voice sound speak audio recording real',title:'Voice playback',text:'Read-aloud uses a voice available on your device, not Sai’s own voice. The portfolio supports adding her recorded answers later, without paying for a voice API.',url:'/contact/'}
];
const stop=new Set('what who is are the a an do does can could how tell me about her she you your his it of to and in with for please experience has have sai keerthana'.split(' '));
function answer(q){const terms=(q.toLowerCase().match(/[a-z0-9]+/g)||[]).filter(t=>!stop.has(t));if(/^(hi|hello|hey|thanks|thank you)[!. ]*$/i.test(q.trim()))return{title:'Hello',text:'Hi! Ask me about Sai’s projects, skills, career, or how to contact her. I search the information in this portfolio.',url:'/experience/'};if(!terms.length&&/who|about|background|experience/i.test(q))return facts[0];const ranked=facts.map(f=>{const keys=f.keys.split(' ');return{f,s:terms.reduce((s,t)=>s+(keys.includes(t)?3:0),0)};}).sort((a,b)=>b.s-a.s);if(!ranked.length||ranked[0].s<3)return{title:'Not in the portfolio',text:'I don’t have a verified answer to that in Sai’s public profile. Ask about a company, project, skill, or contact details—or reach out to Sai directly.',url:'/contact/'};return ranked[0].f;}
if(typeof module!=='undefined'&&module.exports){module.exports={answer,facts};return;}
const launch=document.createElement('button');launch.className='chat-launch';launch.setAttribute('aria-label','Ask about Sai');launch.innerHTML='<span aria-hidden="true">✦</span> Ask about Sai';document.body.appendChild(launch);
const dialog=document.createElement('dialog');dialog.className='profile-chat';dialog.setAttribute('aria-labelledby','chat-title');dialog.innerHTML='<div class="chat-head"><div><span class="kicker">MEET SAI</span><h2 id="chat-title">What would you like to know?</h2></div><button id="chat-close" aria-label="Close assistant">×</button></div><p class="chat-disclosure">Profile assistant · Local answers from the portfolio, not a generative AI model.</p><div id="chat-log" role="log" aria-live="polite" aria-relevant="additions"></div><div class="chat-suggestions"><button data-ask="Tell me about Vatica">Healthcare work</button><button data-ask="What are her skills?">Technical skills</button><button data-ask="How can I contact Sai?">Let’s connect</button></div><form id="chat-form"><label for="chat-input" class="sr-only">Your question about Sai</label><input id="chat-input" maxlength="500" required placeholder="Ask about projects, skills, experience…" autocomplete="off"><button type="submit" aria-label="Send question">↑</button></form><div class="chat-audio"><button id="read-answer" type="button">Read answer aloud</button><button id="stop-audio" type="button">Stop</button><label>Device voice <select id="voice-choice" aria-label="Device voice"></select></label></div><p id="voice-status" class="fine">Uses a device voice, not Sai’s recorded voice.</p>';document.body.appendChild(dialog);
const el=id=>document.getElementById(id);let last=facts[0],speakingAudio=null;
function stopAudio(){if('speechSynthesis'in window)window.speechSynthesis.cancel();if(speakingAudio){speakingAudio.pause();speakingAudio=null;}}
function message(text,type,url,title){const row=document.createElement('div');row.className='chat-message '+type;const p=document.createElement('p');p.textContent=text;row.appendChild(p);if(url){const a=document.createElement('a');a.href=url;a.textContent='Source: '+title+' ↗';row.appendChild(a);}el('chat-log').appendChild(row);row.scrollIntoView({block:'nearest'});}
function ask(q){stopAudio();message(q,'question');last=answer(q);message(last.text,'reply',last.url,last.title);el('chat-input').value='';}
launch.addEventListener('click',()=>{dialog.showModal();if(!el('chat-log').children.length)message('Hi, I can help you explore Sai’s experience. What would you like to know?','reply');el('chat-input').focus();});
el('chat-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{stopAudio();launch.focus();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
el('chat-form').addEventListener('submit',e=>{e.preventDefault();const q=el('chat-input').value.trim();if(q)ask(q);});dialog.querySelectorAll('[data-ask]').forEach(b=>b.addEventListener('click',()=>ask(b.dataset.ask)));
function voices(){if(!('speechSynthesis'in window))return;const current=el('voice-choice').value;el('voice-choice').replaceChildren();window.speechSynthesis.getVoices().forEach(v=>{const o=document.createElement('option');o.value=v.voiceURI;o.textContent=v.name+' ('+v.lang+')';el('voice-choice').appendChild(o);});if(current)el('voice-choice').value=current;}
if('speechSynthesis'in window){voices();window.speechSynthesis.addEventListener('voiceschanged',voices);}else{el('read-answer').disabled=true;el('voice-status').textContent='Voice playback is not supported in this browser. Text chat is available.';}
el('stop-audio').addEventListener('click',stopAudio);el('read-answer').addEventListener('click',()=>{stopAudio();const recording=(window.PORTFOLIO_VOICE_RECORDINGS||{})[last.id];if(recording){speakingAudio=new Audio(recording);speakingAudio.play().catch(()=>el('voice-status').textContent='The recording could not be played.');return;}const u=new SpeechSynthesisUtterance(last.text);u.voice=window.speechSynthesis.getVoices().find(v=>v.voiceURI===el('voice-choice').value)||null;u.rate=.98;u.onerror=()=>el('voice-status').textContent='Voice playback is unavailable. You can still read the response.';window.speechSynthesis.speak(u);});
})();
