import {useState,type CSSProperties} from 'react';
import {Link} from 'react-router-dom';
import {Database,Search,Layers,ChartNoAxesCombined,Network,Workflow,ArrowRight,ArrowUpRight,ChevronLeft,ChevronRight} from 'lucide-react';
const stages=[
 {year:'2016–2018',company:'Goldman Sachs',role:'Data Engineer',theme:'Make data dependable.',icon:Database,color:'#76b7de',skill:'Data foundations',focus:'Document intelligence and data pipelines for legal and compliance workflows.',growth:'Established the foundation: ingestion, document processing, validation, and reliable access to enterprise data.',tools:['Python','Spark','PostgreSQL'],artifact:'Raw records → structured, searchable data',link:'/experience'},
 {year:'2019–2020',company:'Amazon',role:'Data Scientist',theme:'Turn data into relevance.',icon:Search,color:'#87bde9',skill:'Search & ranking',focus:'Search relevance and query resolution through hybrid retrieval and ranking.',growth:'Extended data engineering into modeling: behavioral features, lexical and embedding retrieval, and search evaluation.',tools:['BM25','Embeddings','Airflow'],artifact:'Queries + behavioral signals → ranked results',link:'/work/search-relevance'},
 {year:'2020–2021',company:'Costco Wholesale',role:'ML Engineer',theme:'Make models useful at scale.',icon:Layers,color:'#a9b7ed',skill:'Applied ML',focus:'Enterprise knowledge retrieval and retail analytics.',growth:'Connected models with scalable feature pipelines and enterprise knowledge workflows.',tools:['PySpark','XGBoost','Snowflake'],artifact:'Enterprise knowledge → retrieval & retail insights',link:'/experience'},
 {year:'2022–2023',company:'State of Wisconsin',role:'AI/ML Engineer',theme:'Help teams plan ahead.',icon:ChartNoAxesCombined,color:'#bfb0e6',skill:'Predictive systems',focus:'Demand forecasting and resource planning.',growth:'Applied predictive models and reliable pipelines to planning decisions in the public sector.',tools:['Python','TensorFlow','Azure'],artifact:'Historical patterns → demand forecasts',link:'/experience'},
 {year:'2023–2024',company:'JPMorgan Chase',role:'AI Engineer',theme:'Connect knowledge with AI.',icon:Network,color:'#9bd4ca',skill:'LLM applications',focus:'Financial knowledge services with retrieval, response validation, and Azure delivery.',growth:'Expanded into LLM applications: reusable retrieval and inference services, secure APIs, and production integration.',tools:['Azure OpenAI','LangChain','Weaviate'],artifact:'Financial context → grounded, validated responses',link:'/work/financial-knowledge'},
 {year:'2024–Present',company:'Vatica Health',role:'GenAI Engineer',theme:'Orchestrate the complete workflow.',icon:Workflow,color:'#a8e8c4',skill:'Agentic systems',focus:'Clinical retrieval, governed agents, and healthcare integrations.',growth:'Brought data, retrieval, models, and tools together in stateful agent workflows with evaluation and cloud operations.',tools:['LangGraph','HL7 / FHIR','AWS'],artifact:'Clinical evidence + tools → governed workflows',link:'/work/clinical-intelligence'}
];
export default function CareerJourney(){const [active,setActive]=useState(5);const s=stages[active],Icon=s.icon;return <section className="career-journey" aria-label="Career progression"><div className="journey-heading"><span className="kicker">MY EVOLUTION / 2016—PRESENT</span><span>Select a chapter to explore</span></div><div className="journey-stages" role="group" aria-label="Career chapters">{stages.map((item,i)=>{const Symbol=item.icon;return <button key={item.role} className="journey-stage" aria-pressed={i===active} onClick={()=>setActive(i)} style={{'--stage-color':item.color,'--stage-rise':`${i*13}px`} as CSSProperties}><span className="stage-year">{item.year}</span><span className="stage-sculpture" aria-hidden="true"><span className="stage-base"/><span className="stage-plane plane-one"/><span className="stage-plane plane-two"/><span className="stage-icon"><Symbol size={29} strokeWidth={1.35}/></span></span><span className="stage-role">{item.role}</span><span className="stage-company">{item.company}</span><span className="stage-chapter">0{i+1} <ArrowRight size={13}/></span></button>})}</div><div className="journey-detail" style={{'--chapter-color':s.color} as CSSProperties}><div className="journey-chapter" aria-live="polite"><div className="chapter-heading"><span>CHAPTER 0{active+1} / {s.company}</span><div><button aria-label="Previous career chapter" onClick={()=>setActive((active+5)%6)}><ChevronLeft size={18}/></button><button aria-label="Next career chapter" onClick={()=>setActive((active+1)%6)}><ChevronRight size={18}/></button></div></div><h2>{s.theme}</h2><p>{s.focus}</p><div className="chapter-growth"><span>HOW MY SCOPE EVOLVED</span><p>{s.growth}</p></div><Link className="text-link" to={s.link}>Explore this experience <ArrowUpRight size={16}/></Link></div><div className="journey-system"><div className="system-emblem" aria-hidden="true"><Icon size={54} strokeWidth={1}/></div><span className="system-label">{s.skill}</span><div className="chapter-artifact">{s.artifact.split(' → ').map((part,i)=><span key={part}>{i>0&&<ArrowRight size={19}/>}<b>{part}</b></span>)}</div><div className="chapter-tools">{s.tools.map(t=><span key={t}>{t}</span>)}</div><p>Each chapter builds on the foundations before it.</p></div></div><div className="journey-bottom"><span>DATA FOUNDATIONS</span><div aria-hidden="true"/><span>END-TO-END AI WORKFLOWS</span></div></section>}
