import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {Pause,Play,RotateCcw} from 'lucide-react';
import {useReducedMotion} from '../hooks/useReducedMotion';
const layers=[{name:'Data',title:'Enterprise data & APIs',body:'Validate source schemas, preserve metadata, and enforce document permissions before retrieval.',color:0x55d6bc},{name:'Retrieval',title:'Find the supporting evidence',body:'Combine retrieval, metadata filters, and reranking. Evaluate relevant context independently of answer quality.',color:0x6ed1ed},{name:'Models',title:'Ground the model response',body:'Assemble context, constrain the response, and recognize when evidence is insufficient.',color:0x9aaaff},{name:'Agents',title:'Give every action a boundary',body:'Coordinate workflow state, validate tool arguments, and make handoffs observable.',color:0xba9cf9},{name:'Evaluation',title:'Make quality measurable',body:'Compare golden datasets, grounding, task completion, latency, and runtime traces before a release.',color:0x86edce}];
export default function NetworkScene({expanded=false}:{expanded?:boolean}){
 const host=useRef<HTMLDivElement>(null),reset=useRef<()=>void>(()=>{}),select=useRef<(i:number)=>void>(()=>{});const reduced=useReducedMotion();const [paused,setPaused]=useState(reduced),[active,setActive]=useState(3),[failed,setFailed]=useState(false);const pausedRef=useRef(paused);pausedRef.current=paused;
 useEffect(()=>setPaused(reduced),[reduced]);
 useEffect(()=>{const container=host.current;if(!container)return;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{setFailed(true);return;}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.75));renderer.setClearColor(0x000000,0);renderer.domElement.setAttribute('aria-label','Interactive 3D architecture. Drag to orbit and select a layer with the buttons below.');container.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(40,1,.1,100);camera.position.set(5,3.5,7.5);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.enableZoom=false;controls.autoRotateSpeed=.35;
 scene.add(new THREE.AmbientLight(0xa8c7ff,2));const light=new THREE.DirectionalLight(0xcbe5ff,5);light.position.set(3,6,4);scene.add(light);const rim=new THREE.PointLight(0x50fbd0,20);rim.position.set(-3,1,2);scene.add(rim);
 const group=new THREE.Group();scene.add(group);const selectable:THREE.Mesh[]=[];const resources:{dispose:()=>void}[]=[];
 layers.forEach((layer,i)=>{const geometry=new THREE.BoxGeometry(2.7,.14,2.05),material=new THREE.MeshStandardMaterial({color:layer.color,roughness:.33,metalness:.45,transparent:true,opacity:.72});resources.push(geometry,material);const mesh=new THREE.Mesh(geometry,material);mesh.position.y=(i-2)*.61;mesh.userData.index=i;selectable.push(mesh);group.add(mesh);const edgeGeometry=new THREE.EdgesGeometry(geometry),edgeMaterial=new THREE.LineBasicMaterial({color:layer.color,transparent:true,opacity:.8});resources.push(edgeGeometry,edgeMaterial);mesh.add(new THREE.LineSegments(edgeGeometry,edgeMaterial));});
 const pointsGeometry=new THREE.BufferGeometry();const positions:number[]=[];for(let i=0;i<110;i++){const a=i*2.3999,y=1-i/55,r=Math.sqrt(Math.max(0,1-y*y));positions.push(Math.cos(a)*r*2.7,y*2.7,Math.sin(a)*r*2.7);}pointsGeometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));const pointsMaterial=new THREE.PointsMaterial({color:0x8abdfb,size:.023,transparent:true,opacity:.7});resources.push(pointsGeometry,pointsMaterial);group.add(new THREE.Points(pointsGeometry,pointsMaterial));
 select.current=(idx)=>selectable.forEach((m,i)=>{(m.material as THREE.MeshStandardMaterial).emissive.setHex(i===idx?layers[i].color:0);(m.material as THREE.MeshStandardMaterial).emissiveIntensity=i===idx?.35:0;});select.current(3);
 const observer=new ResizeObserver(()=>{const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});observer.observe(container);
 let visible=true;const intersection=new IntersectionObserver(e=>visible=e[0].isIntersecting);intersection.observe(container);let frame=0;
 const animate=()=>{frame=requestAnimationFrame(animate);if(!visible||document.hidden)return;controls.autoRotate=!pausedRef.current;controls.update();renderer.render(scene,camera);};animate();
 let down={x:0,y:0};const start=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY}};const pick=(e:PointerEvent)=>{if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)return;const box=renderer.domElement.getBoundingClientRect();const ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-box.left)/box.width*2-1,-(e.clientY-box.top)/box.height*2+1),camera);const hit=ray.intersectObjects(selectable,false)[0];if(hit){const index=hit.object.userData.index as number;setActive(index);select.current(index);}};
 renderer.domElement.addEventListener('pointerdown',start);renderer.domElement.addEventListener('pointerup',pick);const lose=(e:Event)=>{e.preventDefault();setFailed(true);};renderer.domElement.addEventListener('webglcontextlost',lose);reset.current=()=>{camera.position.set(5,3.5,7.5);controls.target.set(0,0,0);controls.update();};
 return()=>{cancelAnimationFrame(frame);observer.disconnect();intersection.disconnect();controls.dispose();resources.forEach(r=>r.dispose());renderer.dispose();renderer.domElement.remove();};
 },[]);
 function choose(i:number){setActive(i);select.current(i);}
 return <div className={'webgl-panel '+(expanded?'expanded':'')}><div className="scene-label"><span className="kicker">INTERACTIVE ARCHITECTURE / 3D</span><button className="orbit-motion" onClick={()=>setPaused(p=>!p)} aria-label={paused?'Play motion':'Pause motion'}>{paused?<Play size={13}/>:<Pause size={13}/>}</button></div><div ref={host} className="webgl-stage" hidden={failed}/>{failed&&<p className="webgl-fallback">3D rendering is unavailable on this device. Explore every architecture layer below.</p>}<div className="scene-controls"><span>Drag to orbit · Click a layer</span><button onClick={()=>reset.current()}><RotateCcw size={12}/> Reset</button></div><div className="layer-buttons" role="group" aria-label="Architecture layers">{layers.map((l,i)=><button key={l.name} onClick={()=>choose(i)} aria-pressed={i===active}>{l.name}</button>)}</div><div className="scene-inspector" aria-live="polite"><span className="eyebrow">0{active+1} / {layers[active].name}</span><h3>{layers[active].title}</h3><p>{layers[active].body}</p></div></div>
}
