import {useEffect,useRef,useState,type FormEvent} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {MessageCircle,X,ArrowUp,Volume2,Square} from 'lucide-react';
import {answerProfile,recordings,type ProfileAnswer} from '../lib/profile';
import {useSpeech} from '../hooks/useSpeech';
type Message={id:number;role:'question'|'reply';text:string;answer?:ProfileAnswer};
export default function ProfileAssistant(){const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[messages,setMessages]=useState<Message[]>([{id:0,role:'reply',text:'Hi! Ask me about Sai’s projects, experience, skills, or how to connect.'}]);const dialog=useRef<HTMLDialogElement>(null),input=useRef<HTMLInputElement>(null),log=useRef<HTMLDivElement>(null),launcher=useRef<HTMLButtonElement>(null),next=useRef(1);const speech=useSpeech();const location=useLocation();
 useEffect(()=>{if(open){dialog.current?.showModal();input.current?.focus();}else{dialog.current?.close();speech.stop();}},[open]);
 useEffect(()=>{setOpen(false);},[location.pathname]);
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight});},[messages]);
 const ask=(text:string)=>{if(!text.trim())return;speech.stop();const answer=answerProfile(text);setMessages(m=>[...m,{id:next.current++,role:'question',text},{id:next.current++,role:'reply',text:answer.text,answer}]);setQuery('');input.current?.focus();};
 const submit=(event:FormEvent)=>{event.preventDefault();ask(query);};const last=[...messages].reverse().find(m=>m.answer)?.answer;
 return <><button className="chat-launch" ref={launcher} onClick={()=>setOpen(true)}><MessageCircle size={19}/> Ask about Sai</button><dialog ref={dialog} className="profile-chat" aria-labelledby="chat-title" onClose={()=>{setOpen(false);speech.stop();launcher.current?.focus();}} onClick={event=>{if(event.target===event.currentTarget){const r=event.currentTarget.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)setOpen(false);}}}><div className="chat-head"><div><span className="kicker">MEET SAI</span><h2 id="chat-title">What would you like to know?</h2></div><button aria-label="Close assistant" onClick={()=>setOpen(false)}><X size={20}/></button></div><p className="chat-disclosure">Profile assistant · Answers from the portfolio. No generative model or paid API.</p><div id="chat-log" ref={log} role="log" aria-live="polite" aria-relevant="additions">{messages.map(m=><div className={'chat-message '+m.role} key={m.id}><p>{m.text}</p>{m.answer&&<Link to={m.answer.url}>Source: {m.answer.title} ↗</Link>}</div>)}</div><div className="chat-suggestions">{['Tell me about Vatica','What are her skills?','How can I contact Sai?'].map(q=><button key={q} onClick={()=>ask(q)}>{q}</button>)}</div><form id="chat-form" onSubmit={submit}><label htmlFor="chat-input" className="sr-only">Question about Sai</label><input ref={input} id="chat-input" value={query} onChange={e=>setQuery(e.target.value)} maxLength={500} required placeholder="Ask about Sai’s experience…"/><button type="submit" aria-label="Send question"><ArrowUp size={19}/></button></form><div className="chat-audio"><button disabled={!last||!speech.supported} onClick={()=>last&&speech.speak(last.text,last.id?recordings[last.id]:undefined)}><Volume2 size={13}/> Read aloud</button><button onClick={speech.stop}><Square size={12}/> Stop</button><label>Device voice<select value={speech.selected} onChange={e=>speech.setSelected(e.target.value)}><option value="">Default device voice</option>{speech.voices.map(v=><option key={v.voiceURI} value={v.voiceURI}>{v.name} ({v.lang})</option>)}</select></label></div><p id="voice-status" className="fine">{speech.status}</p></dialog></>;
}
