import {Component,lazy,Suspense,useEffect,useState,type ReactNode} from 'react';
import {Link,NavLink,Route,Routes,useLocation} from 'react-router-dom';
import {Menu,X,ArrowUpRight} from 'lucide-react';
import ProfileAssistant from './components/ProfileAssistant';
import {PageHero} from './components/UI';
const Home=lazy(()=>import('./pages/Home')),Work=lazy(()=>import('./pages/Work')),CaseStudy=lazy(()=>import('./pages/CaseStudy')),Systems=lazy(()=>import('./pages/Systems')),Experience=lazy(()=>import('./pages/Experience')),Contact=lazy(()=>import('./pages/Contact'));
class ErrorBoundary extends Component<{children:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true}}render(){return this.state.failed?<section className="section"><h2>This view could not load.</h2><p>Refresh to try again, or contact Sai directly at saikeerthanat.2614@gmail.com.</p><button className="button primary" onClick={()=>location.reload()}>Reload</button></section>:this.props.children;}}
function RouteEffects(){const {pathname,hash}=useLocation();useEffect(()=>{const names:Record<string,string>={'/':'Senior AI Engineer','/work':'Work & Case Studies','/systems':'Interactive Systems Lab','/experience':'Experience & Skills','/contact':'Work With Me'};const title=names[pathname.replace(/\/$/,'')||'/']||'Enterprise AI Case Study';document.title=title+' | Sai Keerthana';let canonical=document.querySelector<HTMLLinkElement>('link[rel="canonical"]');if(!canonical){canonical=document.createElement('link');canonical.rel='canonical';document.head.appendChild(canonical);}canonical.href='https://saikeerthanat26.github.io'+pathname;if(!hash){window.scrollTo({top:0});return;}const scroll=()=>{const target=document.getElementById(hash.slice(1));if(target){target.scrollIntoView();return true;}return false;};if(scroll())return;const observer=new MutationObserver(()=>{if(scroll())observer.disconnect();});observer.observe(document.getElementById('root')!,{subtree:true,childList:true});const timer=setTimeout(()=>observer.disconnect(),10000);return()=>{observer.disconnect();clearTimeout(timer);};},[pathname,hash]);return null;}
export default function App(){const [menu,setMenu]=useState(false);const location=useLocation();useEffect(()=>setMenu(false),[location]);const navigation=[['/','Overview'],['/work','Work'],['/systems','Systems lab'],['/experience','Experience'],['/contact','Work with me']];return <><RouteEffects/><a className="skip" href="#main">Skip to content</a><header><Link className="brand" to="/">SK<span>/</span><small>Sai Keerthana<span>Senior AI Engineer</span></small></Link><button className="menu-toggle" aria-expanded={menu} aria-controls="nav" onClick={()=>setMenu(m=>!m)} aria-label={menu?'Close navigation':'Open navigation'}>{menu?<X size={20}/>:<Menu size={20}/>}</button><nav id="nav" className={menu?'open':''} aria-label="Main navigation">{navigation.map(([to,label])=><NavLink key={to} to={to} end={to==='/'}>{label}</NavLink>)}</nav><Link className="resume" to="/contact">Let’s connect <ArrowUpRight size={14}/></Link></header><main id="main"><ErrorBoundary key={location.pathname}><Suspense fallback={<div className="route-loading" role="status">Loading portfolio…</div>}><Routes><Route path="/" element={<Home/>}/><Route path="/work" element={<Work/>}/><Route path="/work/:slug" element={<CaseStudy/>}/><Route path="/systems" element={<Systems/>}/><Route path="/experience" element={<Experience/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<PageHero eyebrow="PAGE NOT FOUND" title="Let’s get you back."><Link className="button primary" to="/">Return to portfolio</Link></PageHero>}/></Routes></Suspense></ErrorBoundary></main><footer><Link className="brand" to="/">SK<span>/</span></Link><p>Complex systems. Clear purpose.</p><div><a href="https://www.linkedin.com/in/tsaikeerthana/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://github.com/saikeerthanat26" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="mailto:saikeerthanat.2614@gmail.com">Email ↗</a></div><small>© {new Date().getFullYear()} Sai Keerthana T</small></footer><ProfileAssistant/></>}
